# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish PyPi packages

on:
  push:
    branches: [ "build-work" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - run: pip install '.[dev]'
      - run: python -m build --version
      - run: python -m build .

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
